apiVersion: v1
kind: Service
metadata:
  name: lette-proxy
  annotations:
    load-balancer.hetzner.cloud/location: "nbg1"
    load-balancer.hetzner.cloud/name: "k8s01-lette"
    load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
  labels:
    app: lette-proxy
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: lette-proxy
  ports:
    - name: smtp
      protocol: TCP
      port: 587
      targetPort: 1587
    - name: smtps
      protocol: TCP
      port: 465
      targetPort: 1465
    - name: imap
      protocol: TCP
      port: 143
      targetPort: 1143
    - name: imaps
      protocol: TCP
      port: 993
      targetPort: 1993