
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lette-backend
  labels:
    app: lette-backend
    app.kubernetes.io/name: lette-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lette-backend
  template:
    metadata:
      labels:
        app: lette-backend
    spec:
      containers:
        - name: lette-backend
          image: registry.asdf.ooo/lette-pocketbase:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          volumeMounts:
            - name: pb-data
              mountPath: /pg/pb_data
            - name: litestream-config
              mountPath: /etc/litestream.yml
              subPath: litestream.yml
          env:
            - name: LITESTREAM_REPLICATION_URL
              value: s3://fsn1.your-objectstorage.com/rbs01/lette/backend/data.db
            - name: LITESTREAM_REGION
              value: fsn1
            - name: LITESTREAM_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: litestream
                  key: access-key-id
            - name: LITESTREAM_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: litestream
                  key: secret-access-key
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: secret-key
          
      volumes:
        - name: pb-data
          persistentVolumeClaim:
            claimName: pb-data
        - name: litestream-config
          configMap:
            name: litestream