apiVersion: v1
data:
  litestream.yml: |
    logging:
      level: debug
    dbs:
    - path: /pg/pb_data
      pattern: "*.db"
      recursive: true
      watch: true
      replicas:
        - type: s3
          url: s3://fsn1.your-objectstorage.com/rbs01/lette/backend
          bucket: rbs01
          access-key-id: $LITESTREAM_ACCESS_KEY_ID
          secret-access-key: $LITESTREAM_SECRET_ACCESS_KEY
          endpoint: "fsn1.your-objectstorage.com"
          sync-interval: 10m
          retention: 672h # 4 weeks

kind: ConfigMap
metadata:
  name: litestream


