apiVersion: v1
kind: Secret
metadata:
    name: arcade-slack-api
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:v2HjejbMMK4ZsI0cXi1GpuiYAFud5dUbURcBAWMO2ACOLyFF1l+DzvzF8aI3viUM2e9gLioOXuWUWcK4oJqaEAsyV664t3sFYRmIFVZNRg==,iv:mZPx3UL8NCREcurBffSEcoMyD7ef/SVpUSXVOH2guIc=,tag:tzE2MTYtV9szBBqbx9a8lQ==,type:str]
sops:
    age:
        - recipient: age1afslweztmu653jx7jyea8p56rndztm0vncv8tq6374ly9qn9vfpq0vz5pn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdE1XYTNXdmdjalhKN0gy
            SkF1bEUrRFhYOWFjSmdFZHl5ZXQzS1JtaTAwCkFXenR0TS9Gd1Ztd3FNT3J0RDhu
            cStnY1JWYVg3Z0tzUXh1dHdnV0Yyd1kKLS0tIElmU21WV1RaUWdnSnZzVVAvaExM
            MjgwVHZ5UHJnMkQ3NHphVUI4NC9Ib28K27VvV5sJA/Y0uVhiVIqb7v05X6D287pF
            OLHxRYGZ2qezCHOwcIR0gwvOIViQDfa7OltocCfAbjXbnY58JEOu5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T12:13:49Z"
    mac: ENC[AES256_GCM,data:dFGuWq0xtZdo2nUv3XKUZ6JUCSmr4t4jVjplALEC14m5Fj2vnmRxaLsZiRRbtUgHYkq2VkFPSCjmRj4aLM5wZ6PBGMVXW7UpjfFPdP5ayj+RaJKdeIBQMF0rPs8djwKRCkwpr42IWLzf+J+ij7m+90LCAUVxeruebXPmOLGaKxk=,iv:J+vuAW41l76aNVZUdiZLXFjyrEU4hpXGJJEDZZVBw0c=,tag:Z0TuAekffBv56JwvA6HhZg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|namespace)$
    version: 3.10.2
