resources:
  - ./manifests/lette-backend-deployment.yaml
  - ./manifests/lette-backend-service.yaml
  - ./manifests/lette-backend-ingress.yaml
  - ./manifests/lette-backend-pb-data-pvc.yaml

generators:
  - ./secret-generator.yaml