apiVersion: v1
kind: Service
metadata:
  name: lette-console
  labels:
    app: lette-console
spec:
  selector:
    app: lette-console
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80