---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lette-console
  labels:
    app: lette-console
    app.kubernetes.io/name: lette-console
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lette-console
  template:
    metadata:
      labels:
        app: lette-console
    spec:
      containers:
        - name: lette-console
          image: registry.asdf.ooo/lette-console:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: PB_URL
              value: https://backend.lette.io
            - name: STRIPE_PRICE_ID
              value: price_1LgD0wCz3lzvn3gMY9IgeRMo
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: webhook-secret
            - name: STRIPE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: public-key
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: secret-key
            # - name: SUPABASE_SECRET_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: supabase-key
            #       key: key