apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: node-readyness
  namespace: monitoring
  labels:
    prometheus: k8s
spec:
  groups:
    - name: node-readyness
      interval: 10s
      rules:
        - alert: Kubernetes (k8s) Node Readyness Status
          expr:  kube_node_status_condition{condition="Ready",status="false"} == 1
          for: 0s
          labels:
            arcade_monitoring: "yes"
          annotations:
            icinga2_name: "Kubernetes (k8s) Node {{$labels.node}} Readyness Status"
            icinga2_perfdata_status: "{{$value}};1;1;0;1"
            icinga2_severity: "critical"
            icinga2_vars: |
                sla: 2
            description: "This alert fires when a Kubernetes (k8s) node is not in Ready state."
            prometheus_expression: 'kube_node_status_condition{condition="Ready",status="false"} == 1'
            
        - alert: Kubernetes (k8s) Node Readyness Flapping
          expr:  sum(changes(kube_node_status_condition{status="true",condition="Ready"}[15m])) by (node) > 2
          for: 0s
          labels:
            arcade_monitoring: "yes"
          annotations:
            icinga2_name: "Kubernetes (k8s) Node {{$labels.node}} Readyness Flapping"
            icinga2_perfdata_status: "{{$value}};1;1;0;1"
            icinga2_severity: "critical"
            icinga2_vars: |
                sla: 2
            description: "This alert fires when a Kubernetes (k8s) node is changing its readiness state more than twice in 15 minutes."
            prometheus_expression: 'sum(changes(kube_node_status_condition{status="true",condition="Ready"}[15m])) by (node) > 2'