apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmonitor
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmonitor
  template:
    metadata:
      labels:
        app: alertmonitor
    spec:
      containers:
      - name: alertmonitor
        image: arcadedocker/alertmonitor:latest
        imagePullPolicy: Always
        args:
        ports:
        - containerPort: 9123
        env:
        - name: LOGLEVEL
          value: "info"
        - name: ICINGA2_URL
          value: "https://monitoring.arcade.ch:5665"
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: alertmonitor-config
              key: clustername
        - name: ICINGA2_USERNAME
          valueFrom:
            secretKeyRef:
              name: alertmonitor-icinga2-credentials
              key: username
        - name: ICINGA2_PASSWORD
          valueFrom:
            secretKeyRef:
              name: alertmonitor-icinga2-credentials
              key: password
        - name: PROMETHEUS_URL
          value: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"