apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-namecom
spec:
  acme:
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    For production use this URL instead:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hello@lette.io
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.name.com
          solverName: namedotcom
          config:
            username: rbicker
            apitokensecret:
              name: namedotcom-credentials
              key: api-token