apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/gateway.networking.k8s.io_gatewayclasses.yaml
- manifests/gateway.networking.k8s.io_gateways.yaml
- manifests/gateway.networking.k8s.io_grpcroutes.yaml
- manifests/gateway.networking.k8s.io_httproutes.yaml
- manifests/gateway.networking.k8s.io_referencegrants.yaml
- manifests/gateway.networking.k8s.io_tlsroutes.yaml